### ISSUE TITLE
Методы IVector forEach и applyFunction

### ISSUE THREAD

**Issue by MekhailS** [ThinkingFrog/IVector#10]
Коллеги, предлагаю добавить в интерфейс вектора два метода:
1.
`virtual RC applyFunction(std::function<double(double)> fun) = 0;`
2.
`virtual RC foreach(std::function<void(double)> fun) const = 0;`

Со следующей семантикой:
1. Применить функцию `fun` к каждому элементу вектора и присвоить аутпут этой функции этому элементу, т.е.:
`v[i] = fun(v[i])`
2. Просто применить функцию `fun` к каждому элементу вектора, не меняя сами элементы, т.е.
`fun(v[i])`

Зачем это?
Интерфейс вектора станет гибким и удобным: например, если вдруг кому-то захочется возвести каждую компоненту вектора в квадрат, то не понадобится писать цикл с геттерами-сеттерами или чего хуже вводить новый метод в интерфейс

Зачем `foreach` если будет `applyFunction`?
`foreach` является const методом с немного другой семантикой
(напр. если нам хочется вывести все элементы вектора, то, разумеется, нам не нужно менять его элементы)
К слову, если в foreach прокинуть lambda с списком захвата, то можно красиво реализовать любую логику, которой не требуется знать порядок элементов вектора (напр. выбрать максимальный из элементов вектора, отвечающих заданному условию)

**Comment by MekhailS** [comment]
Стоит отметить, что имплементация обоих методов занимает ~ 3 строчки кода, а сами методы добавляют большую гибкость в будущем
 (разумеется, эти функции можно реализовать для IVector самостоятельно через геттеры и сеттеры, но в таком случае теряется много ресурсов на по сути избыточную логику в геттерах-сеттерах (проверка валидности индекса, и т.п.))

**Comment by AlexeyBurkov** [comment]
Насколько я понимаю `applyFunction` представляет отображение из R^n -> R^n.
1. Не очень представляю зачем такое отображение может быть нужно в контексте того, что мы делаем.
2. Мне кажется, логику действия функции на вектор нужно описывать в функции

`applyFunction` в сравнении с `foreach` представляет очень частный случай. Может быть лучше сделать перегрузку для `foreach`:
`virtual RC foreach(std::function<void(double &)> fun) = 0;`
и тут уже любую логику функции можно сделать, если надо.
Но я всё же не представляю, когда нам может потребоваться такое поведение.

По поводу `foreach`: на самом деле все осмысленные действия связанные с перебором элементов у нас уже есть: умножение на скаляр, скалярное умножение, нормы (за исключением ввывода в стандартный поток наверно).

**Comment by MekhailS** [comment]
Зачем `applyFunction`
- Первый пример который приходит в голову, возвести все компоненты вектора в какую-нибудь степень. Например, чтобы посчитать стандартное отклонение для каждой компоненты
- Сетнуть все компоненты вектора каким-то значением (напр. занулить отрицательные компоненты)
На самом деле можно очень долго приводить примеры отображений Rn->Rn с их юзкейсами, пригодится ли это нам в будущем — неизвестно, я предлагаю сейчас это добавить, потому что это попросту удобно и то же умножение на скаляр можно красиво реализовать через `applyFunction` (к слову, скалярное умножение по сути тоже является отображением Rn->Rn с параметром alpha

`foreach`
Опять же можно представить ситуацию, в которой понадобится перебрать каждую компоненту вектора (напр. отвечает ли каждая компонента какому то условию, вывести компоненты вектора, выбрать минимальную компоненту среди положительных и т.д.). К слову, вычисление норм так же можно реализовать через `foreach`

Касательно перегрузки хз, на мой взгляд правильней отдельно выделить `applyFunction`

**Comment by MekhailS** [comment]
На лекции заходила речь про то, что мы будем реализовывать градиентные методы
Возведение в степень нужна при реализации некоторых адаптивных методов: в RMSProp'е и Adam'е вроде считается экспоненциальная скользящая средняя квадрата градиента

**Comment by AlexeyBurkov** [comment]
Квадрат градиента - это скалярное произведение самого на себя.
Стандартное отклонение можно вычислить с помощью второй нормы.
Не очень понимаю, где нам может потребоваться настолько необычная работа с вектором: нахождение минимума элементов или замена элементов по какому-то сложному правилу. Но пусть будет, не мешает же никому.

И ещё мне кажется никто этим тупо пользоваться не будет, так как это требует построения лямбды (проще цикл написать со ифами), и насколько эти лямбды оптимизированны неизвестно. Может этот дополнительный не нужный if при вызове getCord ухудшит производительность слабее, чем обращение к лямбде.

**Comment by MekhailS** [comment]
Под квадратом вектора v понимается вектор u, у которого u[i] = v[i]^2
Стандартное отклонение каждой компоненты вектора (вектор) невозможно вычислить с помощью второй нормы вектора (скаляр)
