### ISSUE TITLE
А я не понял... (касательно реализации ISet::insert)

### ISSUE THREAD

**Issue by AlexeyBurkov** [ThinkingFrog/IVector#12]
При реализации ISet подразумевается, что в экземпляре будет указатель на блок памяти со всеми векторами?
Или также как с вектором, подряд в памяти лежит экземпляр, а затем вектора?

Если первое, то нахрен нам вообще все эти ухищрения, если всё равно от экземпляра придётся бежать по всей памяти в поисках самих векторов.

Если как с вектором, то как мы можем вообще реалоцировать в методе insert, если эта реалокация похерит старый указатель, а метод insert виртуальный, а не статический...

**Comment by ThinkingFrog** [comment]
Нам нужен динамический массив векторов, поэтому его в любом случае придётся реаллоцировать постоянно. 
Про какие ухищрения ты говоришь?

**Comment by AlexeyBurkov** [comment]
Про то, что мы складываем их вместе в памяти подряд, а не храним массив указателей на вектра, которые в памяти уже где-то лежат в разных местех.
