### ISSUE TITLE
Доделать логгер

### ISSUE THREAD

**Issue by ThinkingFrog** [ThinkingFrog/IVector#14]
В логгер нужно добавить енам уровней логгирования (INFO, ERROR, WARNING хотя бы), автоматизировать прокидывание информации о точке вызова (сейчас это параметры srcfile и line, которые надо передавать руками) и опционально добавить информацию о дате/времени вывода сообщения

**Comment by AlexeyBurkov** [comment]
@ThinkingFrog А разве есть возможность точку вызова определять автоматически? Мне кажется в лучшем случаем можно предложить макрос, который раскрывается в вызов `log(...)` с параметрами `__FILE__`, `__LINE__` и `__func__`:
Примерно так:
```
#define doLog(msg, lvl) log(msg, lvl, __FILE__, __LINE__, __func__)
```
И потом писать:
```
logger->doLog(code, level);
```

**Comment by ThinkingFrog** [comment]
@AlexeyBurkov Да, одна из мыслей примерно такая. Вторая это попробовать с дефолтными аргументами, но я не уверен, пробросятся они правильно или нет
