### ISSUE TITLE
Переименовать NORM::INIFINITE

### ISSUE THREAD

**Issue by ThinkingFrog** [ThinkingFrog/IVector#17]
Это имя пересекается с макросом из windows.h

**Comment by AlexeyBurkov** [comment]
У нас NORM::INIFINITE, он пересакается. Макрос INFINITY тоже существует, определён в `<cmath>`.

**Comment by AlexeyBurkov** [comment]
Издержка из википедии:
"This norm is also called the **supremum norm**, the **Chebyshev norm**, the **infinity norm**, or, when the supremum is in fact the maximum, the **max norm**. The name "**uniform norm**" derives from the fact that a sequence of functions { f n } converges to f under the metric derived from the uniform norm if and only if f n converges to f uniformly."

Можно взять "чебышевскую норму" в качестве названия и не парится (точно проблем не будет).
