### ISSUE TITLE
Переменование cap cup в intersection union

### ISSUE THREAD

**Issue by MekhailS** [ThinkingFrog/IVector#21]
cap и cup не читаемы, давайте переименуем

**Comment by AlexeyBurkov** [comment]
Лично на мой взгляд очень ёмко и понятно. Кто-то это придумал зачем-то, может тут закладывался великий смысл какой-то... Нужно спросить автора

**Comment by ThinkingFrog** [comment]
Я за. Главное чтобы Иванков не был против, но ему вроде пофиг

**Comment by AlexeyBurkov** [comment]
Есть проблема: `union` - ключевое слово в плюсах.

Как вариант можно сделать название `setUnion`, но названия получаются длинные. На мой взгляд `cap` и `cup` прекрасно выглядят.

**Comment by AlexeyBurkov** [comment]
Или, зная семантику методов пересечения и объединения, можно назвать их `makeIntersection` и `makeUnion`.
