### ISSUE TITLE
Проблема с copyInstance внутри get и findFirst

### ISSUE THREAD

**Issue by MekhailS** [ThinkingFrog/IVector#22]
Насколько я понимаю, `ISet::get` и `ISet::findFirst` производят `copyInstance` (deepcopy своего вектора) в участок `IVector* const val`.
Встает вопрос: откуда пользователю знать, сколько памяти требуется для этого конкретного вектора? `IVector::sizeAllocated` может возвращать разные значения в зависимости от имплементации `IVector`.

**Comment by MekhailS** [comment]
Здесь же отмечу, что из-за различных `sizeAllocated`  у нас вектора фактически хранятся в односвязном списке, расположенном в одном участке памяти: 
Для того, чтобы получить i-й вектор необходимо итератором пробежать c 0-го до i-1-го вектора, каждый раз "смещаясь" в памяти на `sizeAllocated`

**Comment by AlexeyBurkov** [comment]
Проблемы нет, есть опечатки: если посмотреть в истории коммитов, я изначально добавил метод `get` в таком же ключе, что и `findFirst`:
Эти методы принимают не константную ссылку на указатель куда будет записан вектор, т.е. память выделяет не сам пользователь, а `ISet`, который в свою очередь может узнать конкретный `sizeAllocated`.

Не знаю, кто и когда удалил амперсанд, но в методе `get` сейчас неверная сигнатура.

**Comment by AlexeyBurkov** [comment]
Пофиксил пропущенный амперсанд.
