### ISSUE TITLE
Модификатор const у val в ISet::get и ISet::findFirst

### ISSUE THREAD

**Issue by MekhailS** [ThinkingFrog/IVector#24]
`virtual RC get(size_t index, IVector const*& val) const = 0;`
`virtual RC findFirst(IVector const * const& pat, IVector::NORM n, double tol, IVector const *& val) const = 0;`

Зачем модификатор const у IVector'а, на который ссылается val? Почему из ISet'а мы не можем достать не константные вектора?

**Comment by AlexeyBurkov** [comment]
Этот модификатор `const` просто запрещает вызывать не константные методы в методе `get` и `findFirst`, потому что а зачем. Передать в этот метод можно и ссылку на указатель на неконстантный вектор. Или не в этом дело?

**Comment by MekhailS** [comment]
> Этот модификатор `const` просто запрещает вызывать не константные методы в методе `get` и `findFirst`, потому что а зачем. Передать в этот метод можно и ссылку на указатель на неконстантный вектор. Или не в этом дело?

Я видимо не совсем понимаю, но как это можно сделать? Каст к const порождает rvalue, как от rvalue можно взять lvalue & ссылку?

**Comment by ThinkingFrog** [comment]
Надо потестить, но кажется Миша прав, const лишний

**Comment by AlexeyBurkov** [comment]
Тогда у нас не должны работать все статические методы в классе вектора. Тогда конструктор копирования нужно было бы писасть в 2х экземплярах. Если я правильно понимаю о чём вы.

**Comment by AlexeyBurkov** [comment]
Всё, понял, был не прав, нужно поменять.
