### ISSUE TITLE
ISet::insert вопрос по поводу первого входного параметра

### ISSUE THREAD

**Issue by AlexeyBurkov** [ThinkingFrog/IVector#28]
Почему мы передаём не константную ссылку на указатель на константный вектор?

**Comment by AlexeyBurkov** [comment]
Почему вот здесь `virtual RC insert(IVector const *& val, IVector::NORM n, double tol) = 0;` val имеет тип не константной ссылки?

**Comment by ThinkingFrog** [comment]
Добавить второй const между * и &?

**Comment by AlexeyBurkov** [comment]
Не знаю, так было на доске изначально написано, я именно спрашиваю.

**Comment by ThinkingFrog** [comment]
Я как раз спрашиваю, в чём предложение? В том, чтобы ещё один const добавить?

**Comment by AlexeyBurkov** [comment]
Я просто не понимаю зачем это, поэтому не могу сказать нужно это или нет, и нужно ли как-то исправить.

**Comment by ThinkingFrog** [comment]
Да наверное опечатка, можно добавить. @MekhailS я прав?

**Comment by MekhailS** [comment]
Да, тут нужно const добавить
