### ISSUE TITLE
Имплементация связи между ISet и ISetIterator

### ISSUE THREAD

**Issue by MekhailS** [ThinkingFrog/IVector#29]
У кого нибудь есть мысли касательно того, как реализовать общение между `ISet` и `ISetIterator`?
Проблема в том, что нам нужно поддерживать постоянную валидность `ISetIterator`'а, т.е.
- при реаллокации массива с векторами в `ISet` `ISetIterator` должен оставаться валидным
- при удалении элемента из `ISet` `ISetIterator` должен оставаться валидным

Первое решение, которое приходит в голову — классически реализовать паттерн Ovserver, где `ISet` — observable, а `ISetIterator`'ы — observer'ы, только проблема в том, что observable должен хранить у себя своих observer'ов, чтобы сообщать им об изменениях. На паре Иванков эту реализацию забанил.
Насколько я услышал, надо сделать что-то типа shared_ptr с control block, но каким образом в нашем случае применима эта концепция?

**Comment by AlexeyBurkov** [comment]
Я полагаю так:
1) контрольный блок как у шаред птр: число ссылок и разделяемый ресурс (указатель на double *)
2) каждый итератор и сам `ISet` разделяют между собой ресурс (удаляется только когда все итераторы и `ISet` уничтожатся)
3) каждый итертор хранит "старый" указатель на ресурс, чтобы можно было узнать, произошла реалокация или нет
4) каждый интератор хранит индекс вектора, чтобы можно было обновить указатель на вектор, которому соответствует итератор, и сам указатель на вектор
5) если при выполнении операции `get` или `next` `old_ptr != ctrl_block->ptr` (значит что произошла реалокация), то нужно пройти по всему набору векторов и найти новый адрес вектора, соответствующего индексу итератора

**Comment by MekhailS** [comment]
Да, это, видимо, рабочий вариант, спасибо

**Comment by MekhailS** [comment]
@AlexeyBurkov а как схендлить `remove`? Реаллокации не происходит, но некоторые итераторы становятся невалидными после этого

**Comment by AlexeyBurkov** [comment]
Да, в контрольный блок текущее число векторов добавить надо.

**Comment by MekhailS** [comment]
Это проблему не решит: если сразу после `remove` сделать `insert`, то кол-во векторов останется прежним, но все итераторы, которые указывали на элементы `ISet`'а, стоящие после того вектора, который удалили, становятся невалидными

**Comment by AlexeyBurkov** [comment]
> Это проблему не решит: если сразу после `remove` сделать `insert`, то кол-во векторов останется прежним, но все итераторы, которые указывали на элементы `ISet`'а, стоящие после того вектора, который удалили, становятся невалидными

Именно эту не пофиксит, и я думаю её пофиксить невозможно, главное не вылететь за пределы массива.

**Comment by AlexeyBurkov** [comment]
Ну по крайне мере, я не знаю как эту проблему пофиксить. Возможно кто-то знает гениальное решение лучше этого, в котором смещение индексов при `remove`'ах будет учтено.

**Comment by AlexeyBurkov** [comment]
На мой взгляд, чтобы решить проблему с удалёнными векторами, нужно хранить что-то вроде истории причём от момента создания, так как мы не знаем, когда именно каждый итератор обновит своё состояние. Такая история будет хранить индексы удалённых векторов т.е. по сути это массив `size_t`.

Но этот массив будет динамически расширяться, и при долгой работе превратится в головную боль.
