### ISSUE TITLE
Предложение метода инкремента и декремента.

### ISSUE THREAD

**Issue by AlexeyBurkov** [ThinkingFrog/IVector#3]
Методы **add** и **sub** создают новые объекты в куче или другом аллокаторе. Такое поведение не оптимально для использования в итерационных численных методах, так как при каждой итерации новое приближение будет получено из метода **add** или **sub**, что породит новый объект.

Предложеине: добавить аналоги методов **add** и **sub**, которые будут выполнять сложение и вычитание "на месте" (в объекте, у которго вызван метод), инкремент и декремент.

Такие методы не создают новые динамические объекты, что улучшит производительность.

**Comment by MekhailS** [comment]
Проще сделать текущие add и sub не статическими и добавить аргумент bool inplace (true — выполнять на месте, вернуть указатель на this, false — вернуть новый вектор)

**Comment by AlexeyBurkov** [comment]
Вроде как эти методы нарочно объявлялись статическими, подчёркивая, что они определяют поведение для всего класса, а не для конкретного объекта.

К слову, зачем их делать не статическими?

Ещё мне кажется, что в варианте `bool inplace` будет сложнее разобраться с семантикой операции (в одном случае нужно сохранять результат в отдельную переменную, чтобы память не утекла, в другом - не нужно), когда `increment(IVector *)` и `decrement(IVector *)` сами за себя говорят.

Ну и последнее. Не нужно будет писать полную реализацию 2х наборов методов. Не inplace можно спокойно выразить через inplace. Т.е. по сути лишней работы не добавляет.

**Comment by ThinkingFrog** [comment]
Я за то, чтобы добавить отдельные нестатические методы. С булевыми флагами все дружно запутаемся рано или поздно. А ещё я бы просто перегрузил операторы + и -, но за такие дела можно получить по рукам от Иванкова, видимо
