### ISSUE TITLE
Новый метод вектору

### ISSUE THREAD

**Issue by ViktorOneLove** [ThinkingFrog/IVector#31]
Было предложение от Иванкова добавить метод вектору, семантика которого — менять текущие данные в векторе на новые

<code>virtual RC setData(double const* const& ptr_data)</code>

**Comment by ViktorOneLove** [comment]
Так как в сете хранятся "сырые" данные, не вектора, чтобы, например, проитерироваться по сету, этот метод был бы полезен, т.к не нужно каждую итерацию создавать новый экземпляр вектора, достаточно создать его один раз до цикла, а в цикле менять данные этого вектора

**Comment by AlexeyBurkov** [comment]
Это небольшое отступление (метод можно добавить, почему нет).

Вообще говоря, создавать и так ничего не нужно для того, чтобы проитерироваться.
При поиске нам нужен единственный метод - `equal`, это сравнение.
Когда храним сырые данные, это сравнение (сравнение не векторов, а сырых данных) можно просто добавить в библиотеку для `ISet` и выполнять сравнения тупо для `double*`. Быстрее и логичнее.

Но при этом разве мы не договорились хранить сами вектора? Если храним сырые данные, то можно в итератор вернуть метод `previous`.

**Comment by MekhailS** [comment]
К сожалению, по всей видимости, выбора у нас нет, Иванков "толкает" нас на реализацию сета через сырые данные. Иначе поддержку вечно валидных итераторов (без множества итераторов внутри сета) сделать, по всей видимости, невозможно. 
Я лично сильно против этого решения, на лекции надо будет его обсудить.

Если остановимся на этой реализации, то `previous` можно вернуть

Дублирование `equal` для даблов это уже что-то за гранью, так делать нельзя

**Comment by AlexeyBurkov** [comment]
Дублирования не будет по факту: мы авторы библиотек - можем сделать статическую либу реализующую `equal` для даблов, и включить её в компиляцию обоих библиотек (set.dll и vector.dll).

Дублирование будет в загружаемых модулях, а это +/- сотня байтов (не уверен, но примерно)... Уж лучше пусть раздувается .dll, чем создавать объекты при итерировании (имхо).

**Comment by MekhailS** [comment]
С помощью предложенного `setData` мы как раз и избегаем проблемы с созданием объектов при итерировании

**Comment by AlexeyBurkov** [comment]
Избегаем только выделения памяти, копирования всё равно происходят.

**Comment by AlexeyBurkov** [comment]
Создал вариант, как ИAA предложил на лекции.
