### ISSUE TITLE
Логгирование, IVector и другие

### ISSUE THREAD

**Issue by Stasychbr** [ThinkingFrog/IVector#32]
В текущей реализации в статических методах IVector (например  static IVector* add(IVector const* const& op1, IVector const* const& op2)) невозможно залоггировать что-либо, так как мы предусмотрели метод для того, чтобы положить логгер в вектор, но не предусмотрели, как его оттуда достать. Нужно либо добавить метод ILogger* getLogger(), либо сделать поле ILogger* _logger статическим для всего интерфейса IVector.

**Comment by Stasychbr** [comment]
Кстати, у ISet ровно такие же проблемы

**Comment by ThinkingFrog** [comment]
Кстати, ты все таки не прав. Если статический метод IVector будет вызывать внутри себя статический метод реализации, то логгер будет доступен даже при подмене бибилиотек

**Comment by AlexeyBurkov** [comment]
А кто мешает написать `VectorImpl::pLogger->log()`? Естественно его нужно сделать публичным предварительно.

**Comment by Stasychbr** [comment]
Мне кажется, мы уже это обсуждали. В статические функции IVector могут приходить чужие реализации, это требование Иванкова. Тогда при прокидывании этих векторов в статический метод вашей реализации может произойти segfault из-за обращения по кривому смещению в поисках поля под логгер. При втором подходе ситуация аналогична.
Что мешает написать virtual ILogger* IVector::getLogger() const = 0?

**Comment by AlexeyBurkov** [comment]
Обращение будет не по кривому смещению, а к своему собственному полю внутри своей собственной библиотеки, чей статический метод был вызван. Никаких сегфолтов не будет. Т.е. мы будем брать свой логгер, а не чужой, раз статический метод вызван у нас. В этом смысле логгер - тупо статическая переменная внутри библиотеки.

Если добавить такой метод, то будут возникать разночтения: а чей логгер брать для того, чтобы залогать ошибку.

**Comment by Stasychbr** [comment]
Окей, да будет так
