### ISSUE TITLE
Эффективное получение вектора из ISet 

### ISSUE THREAD

**Issue by Stasychbr** [ThinkingFrog/IVector#33]
В текущей реализации единственный метод, который предназначен для извлечения вектора из сета - это RC get(size_t index, IVector const*& val) const. То есть в случае, когда в сете лежат полноценные вектора, то возвращается просто указатель на элемент сета, но если хранятся сырые данные, то приходится конструировать вектор на куче и инициализировать его координатами из сета. Это как минимум долго и неэффективно. 
Нужно предусмотреть метод, который позволяет менять вектор, проинициализированный заранее на стороне клиента. Что-то вроде RC getCoords(size_t index, IVector*& val) const, а старый переименовать в RC getVector(size_t index, IVector const*& val) const.

**Comment by AlexeyBurkov** [comment]
В любом случае возвращается копия, даже если мы целый вектор храним. Указатель вернуть нельзя, иначе при каком-то инсерте все ранее полученные указатели заруинятся.

**Comment by Stasychbr** [comment]
Тогда тем более нужен метод, чтобы можно было не брать память с кучи при простом извлечении данных из контейнера.

И, кстати, эта вещь с копией весьма неочевидна, как по мне. Есть предложение переименовать get() в getCopy(), чтобы пользователь точно знал, что ему потребуется самостоятельно вызвать delete.

**Comment by AlexeyBurkov** [comment]
А как не брать память с кучи? В любом случае нельзя возвращать указатель на данные внутри контейнера - провоцирует проблемы.

Переименовать можно.

**Comment by Stasychbr** [comment]
Пользователь может создать буферный вектор с нужной размерностью на своей стороне с произвольными координатами, и сет будет писать нужные координаты в этот вектор при каждом запросе на извлечение данных, тогда будет всего один вызов памяти с кучи.

**Comment by Stasychbr** [comment]
Нужно просто сделать метод, в который можно передать неконстантный вектор

**Comment by AlexeyBurkov** [comment]
И ещё гарантированно нужно добавить метод `setData`.

**Comment by Stasychbr** [comment]
Если не хотим бегать циклом по координатам - то да

**Comment by AlexeyBurkov** [comment]
Я думаю то же самое касается `findFirst`.

На данный момент уже есть перегрузка этих методов с неконстантным вектором (в отдельной ветке, есть пул реквест), необходимость которых возникла из того, что lvalue ссылка на указатель на неконстантный вектор не кастуется на lvalue ссылку на указатель на константный вектор.

Эти методы обозначаем как copy, и добавляем методы, которые реализуют получение данных без выделения памяти, так полагаю?

**Comment by Stasychbr** [comment]
Было бы логично, да

**Comment by AlexeyBurkov** [comment]
А как назвать? `copyDataFrom` или что-то подобное?

**Comment by Stasychbr** [comment]
getCoords для индекса и getCoordsFirst для findFirst?

Вроде бы у нас до этого не было какой-то строгой нотации, поэтому не принципиально
