### ISSUE TITLE
Интерфейс IControlBlock

### ISSUE THREAD

**Issue by OvechkinDanil** [ThinkingFrog/IVector#41]
На прошлой паре Иванков говорил про добавление нового интерфейса. Он разделяет ресурс, который располагает ISet и iterator. Как он объяснил, итераторы запрашивают доступ к ISet через этот интерфейс.
Он предложил следующее:
- Добавить в реализацию Set'а массив size_t, в котором будут храниться уникальные индексы каждого элемента. Если мы удалим какой-то элемент, то другому элементу нельзя присвоить такой индекс. 
- Добавить в интерфейс IControlBlock только этот метод: virtual RC get(size_t& index, IVector* pVector) = 0;
  В index мы кладем текущий индекс, и получаем из него следующий. Ну и в pVector мы кладем уже выделенную память по IVector, чтобы соответственно получить нужный нам вектор.

**Comment by AlexeyBurkov** [comment]
А это разве не внутренний интерфейс реализации? Зачем клиенту знать, что у нас есть какой-то внутренний интерфейс. Он его создать никак не сможет и использовать тоже. В чём резон его вводить? Или подразумевается, что наши итераторы тоже должны быть взаимозаменяемы как всё остальное, поэтому для работы требуется унификация интерфейса?

**Comment by OvechkinDanil** [comment]
Да, возможно я его не так понял.

**Comment by AlexeyBurkov** [comment]
Я тоже мог не так его понять, поэтому спрашиваю. Думаю стоит уточнить завтра.

**Comment by AlexeyBurkov** [comment]
Получается получение следующего элемента `ISet` в итераторе (метод `IControlBlock::get`) будет иметь алгоритмическую сложность линейную? Конечно можно улучшить до логарифма, если применять бинарный поиск, но всё равно поиск.

**Comment by MekhailS** [comment]
Да, получается логарифм

**Comment by AlexeyBurkov** [comment]
Похожий контролбный блок нужно добавить для итератора компакта полагаю?
