### ISSUE TITLE
Перегрузки интерфейсных методов 

### ISSUE THREAD

**Issue by Stasychbr** [ThinkingFrog/IVector#42]
Иванков запретил перегрузку методов в публичном интерфейсе. У нас появились перегрузки в IVector #30, ISet #24 и может даже где-то еще. 
Считаю, что необходимо убрать эти методы для константных аргументов. Из ISet мы возвращаем всегда deep copy, кому нужна константная копия ресурса? moveInstance уничтожает источник данных, зачем делать этот источник константным?

**Comment by AlexeyBurkov** [comment]
`moveInstance`: источник может быть константным изначально, если удалить этот метод, то мы не сможем сделать `move` с константного вектора.
другие методы: мы передаём в те методы lvalue ссылку на указатель. Чтобы иметь возможность записать адрес deep копии в константный указатель, нужно перегружать.

**Comment by AlexeyBurkov** [comment]
Если на это действительно пофиг, то можно удалить.

**Comment by Stasychbr** [comment]
Насчет move, мне кажется, это проблема клиентского кода, пусть снимают копию. Если кому-то понадобится зачем-то константная копия вектора, то в любом случае перегрузки запрещены. Кажется, проще удалить.

**Comment by AlexeyBurkov** [comment]
Ок

**Comment by ThinkingFrog** [comment]
Есть ещё перегрузка в конструкторе логгера, но я сомневаюсь, что она мешает

**Comment by AlexeyBurkov** [comment]
Ему на логгер пофиг, и эти библиотеки как он сказал, мы будем сообщать на этапе компиляции, соответственно никаких дополнительных проблем с получением этих функций не должно быть.
Проблемы могли бы быть при динамическом подключении и обращении к функциями как он показывал на лекции.
Думаю затестим, если уже не затестили, и всё ок будет.
