### ISSUE TITLE
Методы проверки позиции итератора

### ISSUE THREAD

**Issue by MekhailS** [ThinkingFrog/IVector#49]
Необходимо добавить методы проверки итератора на то, находится ли он в конце и в начале.

`equal()` с `getBegin()` и `getEnd()` не подходят, т.к. в случае, если итератор находится на векторе с хешем > хеша у итератора из `getEnd()`, то мы не сможем понять, что этот итератор в действительности находится в конце.

**Comment by AlexeyBurkov** [comment]
А как это вообще может произойти?
Я думаю, можно смело считать обязаностью клиента контролировать состояние итераторов после удаления и так далее. Если в множество добавили новый вектор, то старый итератор, полученный из `getEnd` ранее, очевидно уже не последний итератор.

**Comment by MekhailS** [comment]
Допустим, было множество из 10 векторов.
Взяли итератор itA, указывающий на 7-й вектор.
Удалили из множества вектора с 5 по 10

itA все еще хранит в себе 7-й вектор.
getEnd возвращает итератор на 5 вектор.

itA находится в конце (правей сдвинуться он не может), но он не равен итератору из getEnd

Обязанности следить за удалением и добавлением векторов в сет у клиента нет, вся эта песня с контрл блоком и хешами делается ради того, чтобы итераторы были всегда валидны

**Comment by AlexeyBurkov** [comment]
itA ссылается на элемент, которого в ISet уже нет, но при дальнейшем использовании itA он будет валидным.
Сравнивать такой итератор нет смысла, так как он ссылается на удалённый элемент вектора, т.е. итератор ссылается на элемент множества `-A`, пусть исходное множество - `A`. За адекватность таких операция как раз отвечает пользователь.

Валидность заключается в том, что действия совершаемые с итератором не приведут к падению программы. Мы же сваливаем ответственность на клиента и гарантируем ему неопределённое поведение при сравнении итарторов, принадлежащих разным множествам, что вполне логично. Это частный случай сравнения итераторов из разных множеств.

**Comment by MekhailS** [comment]
Итератор привязан к множеству `A`, множества `-A` нет, как и итераторов на него.

Касательно сравнения итераторов претензий нет, текущее поведение логично и его трогать не надо. (итераторы ссылаются на разные элементы => они не равны)

Проблема в том, что мы в итоге не сможем посмотреть, находится ли итератор `itA` в конце (или в начале), т.е. сможем ли мы сдвинуться на `next`(`previous`), получив новый элемент

**Comment by AlexeyBurkov** [comment]
На мой взгляд эта проблема не имеет решения для итераторов, которые ссылаются на удалённый элемент, потому что при выполнении операции `getNext/Previous` с таким итератором, результат будет отличаться от обычного поведения: итератор сместится на вектор с ближащим валидным хэшем сета.

Т.е. если у нас итератор itA ссылался на 7-ой вектор, а клиент удалил 7 и 8, то при выполнении операции `getNext(1)`, итератор переедет на 9-ый вектор.

Я считаю разумным обозвать такое использование итераторов (сравнение с такими итераторами) неопределённым поведением и забить.

**Comment by MekhailS** [comment]
Сравнение корректно

Если добавить два метода на проверку, находится ли сам итератор в конце или в начале (может ли он сместиться на новый элемент направо или налево), то проблема решится
