### ISSUE TITLE
Заменить все указатели на std::unique_ptr

### ISSUE THREAD

**Issue by ThinkingFrog** [ThinkingFrog/IVector#5]
Рано или поздно утечки памяти станут слишком большой проблемой и разумнее сразу начать использовать умные указатели

**Comment by AlexeyBurkov** [comment]
Утечки памяти вызванные забытыми delete'ами? Или ещё какие-то утечки есть?
И ещё. Мы же можем и так пользоваться умными указателями без изменения типов параметров.

**Comment by MekhailS** [comment]
Почему std::unique_ptr? Насколько я понял, у нас несколько поинтеров могут менеджить одним объектом, что с помощью std::unique_ptr вроде как делать нельзя.
Если использовать std::shared_ptr, то все проблемы с утечками памяти уйдут моментально

**Comment by AlexeyBurkov** [comment]
Я от 4го курса слышал, что Иванков не любит, когда везде пишут умные указатели. Мне кажется можно самостоятельно (уже в клиентском коде, а не в коде библиотеки) использовать их, т.е. без внедрения в интерфейс.

И ещё раз уточню: о каких утечках памяти идёт речь, может я что-то не понимаю?

**Comment by ThinkingFrog** [comment]
@AlexeyBurkov Вот ты хочешь использовать результат сложения как временный объект, чтобы просто вывести в поток вывода. Пишешь (допустим у нас есть перегрузка вывода указателя на IVector в поток)
`std::cout << IVector.add(...) << std::endl;`
И получаешь утечку, потому что объект внутри add создан, но нигде не удалён
Нужно создавать указатель, который примет результат add, а потом его ещё руками удалить. Первое, что пришло в голову на самом деле, примеры где можно потерять указатель случайно можно придумывать целыми днями

**Comment by ThinkingFrog** [comment]
В целом да, мелькала в голове мысль использовать умные указатели в клиентском, а не библиотечном коде, чтобы не триггерить Иванкова. В самой библиотеке утечки вряд ли будут, а использовать их у себя или нет, пусть будет на совести каждого отдельного человека

**Comment by AlexeyBurkov** [comment]
Думаю, если очень хочется, можно это дело уточнить у самого Иванкова, я только слышал, что ему не нравится так.

А так, с умными указателями станет писать проще. Но разница между "использовать только у себя в коде" и "использовать в бибилотеке" - минимальная: просто придётся писать или не писать `.get()` при вызове функций.
