### ISSUE TITLE
Вопрос по новому методу

### ISSUE THREAD

**Issue by AlexeyBurkov** [ThinkingFrog/IVector#55]
Как предполагается реализовывать метод `isValid`?

Как вообще теперь мы работаем с итераторами, вектора которых удалены из множества.

**Comment by Stasychbr** [comment]
isValid() возвращает true, если итератор еще можно двигать по элементам множества. То есть даже если итератор указывает на удаленный элемент множества, он остается валидным. false возвращается в случае, если итератор "отработал" сет (у него вызвали next() на последнем элементе или previous() на первом). Тогда у него в индексе записывается наибольший size_t, и можно лишь переназначить итератор на начало или конец сета методами makeBegin() и makeEnd(), двигать его из этого состояния нельзя.

**Comment by AlexeyBurkov** [comment]
ок, понял, спасибо
