### ISSUE TITLE
Новый метод ISetControlBlock 

### ISSUE THREAD

**Issue by Stasychbr** [ThinkingFrog/IVector#56]
Есть предложение добавить контрол блоку виртуальный метод InvalidateSet(), который сет у него дергает в своем деструкторе (потому что сейчас я не очень понимаю, как контрол блок понимает, жив ли сет)

**Comment by AlexeyBurkov** [comment]
На мой взгляд не очень хорошо так делать, так как все итераторы получат возможность этим методом воспользоваться.

Я делаю следующим образом: в сете храню указатель на реализацию контрольного блока, а в итераторы передаю как указатель на интерфейс. В итоге можно в реализацию дописать какие угодно методы, итераторы не имеют к ним доступа.

**Comment by Stasychbr** [comment]
Я храню указатель на реализацию сета в контрол блоке, мне нужны некоторые методы реализации сета. В самом сете приходится хранить указатель только на интерфейс блока во избежание ошибки линковки. В этом случае придется делать dynamic_cast в деструкторе, чего не хочется. Эта проблема решается как-то иначе, может есть способ хранить указатель на реализации и там, и там?

**Comment by AlexeyBurkov** [comment]
А почему могут быть ошибки линковки?
Я понял, что контрольный блок - просто кусок реализации сета, имеющий собственный интерфейс.

**Comment by Stasychbr** [comment]
Если в двух .h файлах прописать #include друг на друга, то линковщик ругается. Если прописать в одном .h файле (пусть в SetImpl.h) class ControlBlockImpl;, то все будет хорошо до того момента, как попытаться дернуть метод из ControlBlockImpl (напишет, что недоопределен класс). Если в SetImpl.cpp прописать в добавок к предыдущему #include "ControlBlock.h", то будет ошибка линковки из-за множественного определения класса. Вчера долго думал над этой проблемой, так ничего и не придумал.

А что ты хранишь в контрол блоке? Указатель на интерфейс сета?

**Comment by AlexeyBurkov** [comment]
Нет, храню указатель на реализацию.
Но я ещё итератор свой не тестил и видимо не компилировал.
Раз нужно то давайте новый метод.

**Comment by Stasychbr** [comment]
Не уверен, что нужно, может и есть решение, которое позволит скомпилировать такой код. Предлагаю подождать, пока Дима прокомментирует это

**Comment by AlexeyBurkov** [comment]
> Если в двух .h файлах прописать #include друг на друга, то линковщик ругается. Если прописать в одном .h файле (пусть в SetImpl.h) class ControlBlockImpl;, то все будет хорошо до того момента, как попытаться дернуть метод из ControlBlockImpl (напишет, что недоопределен класс). Если в SetImpl.cpp прописать в добавок к предыдущему #include "ControlBlock.h", то будет ошибка линковки из-за множественного определения класса. Вчера долго думал над этой проблемой, так ничего и не придумал.

А если написать `class ControlBlockImpl;`, а потом в `SetImpl.cpp` сделать `#include "ControlBlockImpl.h`?

**Comment by AlexeyBurkov** [comment]
У меня всё ок собралось. Я даже не в .cpp инклюды писал, а просто в .h добавил по форвард декларации, и компилятор успокоился.

**Comment by Stasychbr** [comment]
Да, мой косяк где-то. Вчера буквально эта же идея выдавала ошибку ambigous class declaration или что-то в этом роде. Сорян за потраченное время
