### ISSUE TITLE
Compact control block

### ISSUE THREAD

**Issue by Stasychbr** [ThinkingFrog/IVector#57]
Нам нужен отдельный интерфейс под контрольный блок для итераторов компакта? Если да, могу завтра накидать код.

**Comment by AlexeyBurkov** [comment]
Пул реквест уже есть. Лучше ISolver сделай, его точно нет.

**Comment by AlexeyBurkov** [comment]
Критика по контрольному блоку приветствуется.

**Comment by Stasychbr** [comment]
Мы тут обсудили немного итерирование. Что будет, если на компакте сменится сетка? По идее надо сетку итераторов масштабировать на новую, что проблематично. Я вижу выход в виде хранения внутри итератора только вектора, а там компакт пусть сам решает, приводить этот вектор к своей сетке и делать сдвиг или сразу двигать. В таком случае надо поправить контрольный блок, потому что мультииндекс итератору просто не нужен. Есть иные соображения по этому поводу?

**Comment by AlexeyBurkov** [comment]
Звучит разумно и проще.

**Comment by AlexeyBurkov** [comment]
Я думаю, этот вопрос закрыт.
