### ISSUE TITLE
Нужны ли геттеры для границ компакта?

### ISSUE THREAD

**Issue by AlexeyBurkov** [ThinkingFrog/IVector#66]
На данный момент границы можно получить, например из итератора или по индексу.

**Comment by Stasychbr** [comment]
В принципе, можно обойтись и итераторами. Нужно, чтобы кто-нибудь еще высказался по этому поводу

**Comment by AlexeyBurkov** [comment]
С одной стороны итераторы будут оверкилом для получения границ, с другой стороны это лаба...

**Comment by Stasychbr** [comment]
Ну в принципе весь вопрос занимает строчек 10, учитывая интерфейс и реализацию, наверное, стоит добавить

**Comment by AlexeyBurkov** [comment]
А как сделать эти методы? Чтобы они новый вектор строили или копировали данные в буффер?

**Comment by Stasychbr** [comment]
deep copy наверное проще для клиентского кода
