### ISSUE TITLE
Начало и конец компакта

### ISSUE THREAD

**Issue by AlexeyBurkov** [ThinkingFrog/IVector#67]
Наш компакт имеет итератор, для получения итератора есть методы `getBegin`, `getEnd`. У нас есть договорённость о том, что эти штуки делают: что есть конец и что есть начало?

Нужно либо удалить их нахрен, либо зафиксировать какую-то семантику.

**Comment by AlexeyBurkov** [comment]
Если удалим, то нужно что-то делать с получением границ компакта.

**Comment by Stasychbr** [comment]
Кажется логичным выдавать итераторы с граничными векторами.

**Comment by AlexeyBurkov** [comment]
Я кароче это в описании зафиксирую.
