### ISSUE TITLE
Имплементация `createIntersection`

### ISSUE THREAD

**Issue by AlexeyBurkov** [ThinkingFrog/IVector#68]
Мы допускаем создание вырожденных компактов или нет? От этого зависит наличие параметра точности. Его можно убрать, если мы не создаём вырожденные компакты. Он нужен, если мы создаём вырожденные компакты.

**Comment by Stasychbr** [comment]
У меня в тетради записан вариант с нормой и точностью. Мы вроде обсуждали компакты меньшей размерности, было такое. В таком случае договорились писать 0 в число шагов по той оси, которой нет

**Comment by Stasychbr** [comment]
Непонятно правда, как реализовать пересечения. У нас нет геттеров для границ компакта 
А, можно по индексу попросить вектор. Вопрос снимается.

**Comment by AlexeyBurkov** [comment]
Может быть сделать чистые методы, мне кажется разумно. Не нужно будет создавать экземпляр мульти-индекса только ради получения краёв.

**Comment by AlexeyBurkov** [comment]
> У меня в тетради записан вариант с нормой и точностью. Мы вроде обсуждали компакты меньшей размерности, было такое. В таком случае договорились писать 0 в число шагов по той оси, которой нет

Норма, мы же выяснили, не нужна. Она нужна для множества, так как мы поэлементно сравниваем, а тут упорядоченное множество, поэтому норму не нужно добавлять.
