### ISSUE TITLE
`IMultuIndex::incAxisIndex`

### ISSUE THREAD

**Issue by AlexeyBurkov** [ThinkingFrog/IVector#69]
В этом методе изменили тип `ssize_t` на `size_t`.

Либо этот метод убрать, и будем обходится `set...` всякими. Либо нужно вернуть знаковость типа, чтобы была возможность не только увеличить, но и уменьшить индекс.

**Comment by ThinkingFrog** [comment]
gcc кидал ошибки на ssize_t. Если там предполагался знаковый инт, то почему сразу его и не написать?

**Comment by AlexeyBurkov** [comment]
Потому что знаковый `int` маленький слишком. `ssize_t` определён в другом заголовочнике. Можно добавить например `<cstdlib>`.

**Comment by ThinkingFrog** [comment]
![image](https://user-images.githubusercontent.com/40119009/115989184-daa02200-a5c5-11eb-9d68-0a11eea51c6f.png)
cstddef подключен

**Comment by ThinkingFrog** [comment]
Подключил stdlib и вернул ssize_t
