### ISSUE TITLE
Иванков просил добавить метод в вектор

### ISSUE THREAD

**Issue by AlexeyBurkov** [ThinkingFrog/IVector#7]
Иванков просил добавить метод связанный кажется с получением объёма выделенной памяти под весь вектор, в контексте описания эффективного способа хранения вектора. Что-то вроде `virtual size_t sizeof...() = 0`.

Сам точно не запомнил ни название, ни смысл, может кто-то помнит?

**Comment by ThinkingFrog** [comment]
Чем это будет отличаться просто от вызова sizeof() на объект?

**Comment by AlexeyBurkov** [comment]
Он говорил про то, что хранение элементов как `dobule *` вызовет проблемы в случае, если место в куче, где лежит IVector, и место, где лежат сами элементы вектора, будут удалены друг от друга (будет cache miss у процессора при работе с вектором (достать элемент вектора например), и ему придётся подгружать из оперативки в кеш совершенно другой участок памяти, собственно где лежат элементы).
Поэтому эффективнее выделить память сплошником для объекта и для массива элементов, потом вызвать placement new для объекта и инициализировать элементы в оставшейся памяти.

В связи с этим он сказал, что нужно знать информацию о реальном количестве памяти, выделенной под объект, или что-то такое.

**Comment by AlexeyBurkov** [comment]
Это же самое он говорил по поводу ISet (что можно также хитро хранить). И получается для ISet нужна будет информация о том, сколько действительно занимает 1 объект вектора, чтобы выделить достаточно памяти.

**Comment by AlexeyBurkov** [comment]
Визуализация [наивного подхода](https://github.com/ThinkingFrog/IVector/files/6078423/temp.pdf) и [то, что описал Иванков.](https://github.com/ThinkingFrog/IVector/files/6078431/temp1.pdf)
