### ISSUE TITLE
О семантике byPassOrder

### ISSUE THREAD

**Issue by KoloskovAleksandr** [ThinkingFrog/IVector#72]
Предлагаю изменить (или установить?) семантику значений в мультииндексе порядка обхода - лучше бы если значения в byPassOrder были значениями осей, а не значениями порядка осей, потому что в нынешней ситуации приходится держать функцию-поисковик (по крайней мере нулевого индекса) и на стороне итератора, и на стороне компакта.
В таком случае {2 0 1} определяет порядок {z, x, y} (а не порядок {y, z, x}). Тогда итератору не придется заботится о переменной инкрементации, он просто обратится к orderByPass[0].

**Comment by AlexeyBurkov** [comment]
Я полагаю ожидается, что это должно появится в описании?

**Comment by KoloskovAleksandr** [comment]
Вроде того

**Comment by AlexeyBurkov** [comment]
Проверь, что правильно тебя понял.
