### ISSUE TITLE
О валидации итератора по компакту

### ISSUE THREAD

**Issue by KoloskovAleksandr** [ThinkingFrog/IVector#73]
Необходимо добавить итератору по компакту метод  bool isValid(), семантически аналогичный методу итератора по множеству.

**Comment by KoloskovAleksandr** [comment]
Коль скоро мы решили, что итератор ходит только вперед, можно подменить isValid чем-то вроде isAtEnd

**Comment by AlexeyBurkov** [comment]
А зачем этот метод?

**Comment by AlexeyBurkov** [comment]
P.S. Я не понимаю его смысл в сете, поэтому и тут не понимаю...

**Comment by Stasychbr** [comment]
Идея в том, чтобы писать вещи вроде while(iterator->isValid()) {...; iterator->next();}

**Comment by AlexeyBurkov** [comment]
Можно писать:
```
RC rc = RC::SUCCESS;
while (rc == RC::SUCCESS)
{
    ...
    rc = iterator->move();
}
```

**Comment by AlexeyBurkov** [comment]
Кстати, мб метод, который двигает итератор, переименовать на `next`?

**Comment by AlexeyBurkov** [comment]
Переименовал.

Всё же я не понимаю, чем возвращаемый `RC` хуже? То же самое могу сказать про итератор сета, но его менять не будем, уже делать все начали его.

**Comment by Stasychbr** [comment]
В принципе, можно и не делать, хотелось соблюсти единство стиля с сетом

**Comment by AlexeyBurkov** [comment]
Ок

**Comment by AlexeyBurkov** [comment]
Проверьте пр, правильно ли

**Comment by Stasychbr** [comment]
Кажется, все окей
