### ISSUE TITLE
Вопрос по `IBroker`

### ISSUE THREAD

**Issue by AlexeyBurkov** [ThinkingFrog/IVector#80]
Разве не нужно вынести объявление фабричного метода в щаголовочный файл? Или типо мы силой мысли знаем что эта штука там есть?

**Comment by AlexeyBurkov** [comment]
А ещё кажется что в интерфейсе брокера должно быть что-то связанное с установкой логгера.

**Comment by ThinkingFrog** [comment]
Фабрика не должна торчать из интерфейса, она нужна для загрузки из длл, я ещё на лекции спрашивал

**Comment by ThinkingFrog** [comment]
Не знаю, насколько там нужен логгер. Если кто-то доберётся до брокера и он ему понадобится, то добавим

**Comment by AlexeyBurkov** [comment]
Не, я имею в виду логгер не для брокера, а для словера и проблемы. Доступ к статическим методам как я понимаю только через брокера или нет?

**Comment by AlexeyBurkov** [comment]
И в брокере в поддерживаемых типах только солвер и просто проблема. Мы дифференцируемую проблему не трогаем? Т.е. и градиентные методы не приминяем?

**Comment by ThinkingFrog** [comment]
Код полностью переписанный с доски во время лекции. У меня тоже к нему много вопросов, но с ними надо сначала идти к Иванкову

**Comment by ThinkingFrog** [comment]
Конкретно по описанным здесь вопросам на лекции не было ни слова, писали наспех и вполне вероятно, что что-то просто забыли

**Comment by AlexeyBurkov** [comment]
Ок
